import type { CutterExportResult, CutterProject, PieceSourceFile } from '../types'
import { escapeXml, getPlacedArtworkRect, getPlacedCutlineSvgElement } from './cutlineGenerator'

export async function exportCutterSvg(project: CutterProject): Promise<CutterExportResult> {
  const { sheet, sources, pieces, placedPieces, layers, exportSettings } = project
  const pieceMap = new Map(pieces.map((piece) => [piece.id, piece]))
  const sourceMap = new Map(sources.map((source) => [source.id, source]))
  const artworkMarkup = exportSettings.includeArtwork
    ? await Promise.all(
        placedPieces.map(async (placed) => {
          const piece = pieceMap.get(placed.presetId)
          const source = piece ? sourceMap.get(piece.sourceId) : undefined

          if (!piece || !source) {
            return ''
          }

          const rect = getPlacedArtworkRect(placed, piece)
          const href = await sourceToDataUrl(source)
          const transform = rect.rotation
            ? ` transform="rotate(${rect.rotation} ${rect.xCm + rect.widthCm / 2} ${rect.yCm + rect.heightCm / 2})"`
            : ''

          return [
            `<g id="artwork_${escapeXml(placed.id)}" data-piece="${escapeXml(piece.displayName)}">`,
            `<image href="${href}" x="${rect.xCm}cm" y="${rect.yCm}cm" width="${rect.widthCm}cm" height="${rect.heightCm}cm" preserveAspectRatio="none"${transform} />`,
            '</g>'
          ].join('')
        })
      )
    : []
  const cutlineMarkup = exportSettings.includeCutlines
    ? placedPieces
        .map((placed) => {
          const piece = pieceMap.get(placed.presetId)

          return piece ? getPlacedCutlineSvgElement(placed, piece) : ''
        })
        .join('\n')
    : ''

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="${sheet.widthCm}cm" height="${sheet.heightCm}cm" viewBox="0 0 ${sheet.widthCm} ${sheet.heightCm}">
  <title>Cutter Montage ${sheet.widthCm}x${sheet.heightCm}cm</title>
  <desc>Generated by My Printer App by Maher Tka. Cutline vectors are grouped under CutContour.</desc>
  <rect id="Artboard" x="0" y="0" width="${sheet.widthCm}" height="${sheet.heightCm}" fill="#ffffff" />
  <g id="Artwork" inkscape:label="Artwork" data-layer-visible="${layers.artwork}">
${artworkMarkup.join('\n')}
  </g>
  <g id="CutContour" inkscape:label="${escapeXml(exportSettings.strokeName)}" data-spot-name="${escapeXml(exportSettings.strokeName)}" data-layer-visible="${layers.cutlines}">
${cutlineMarkup}
  </g>
</svg>`

  return {
    blob: new Blob([svg], { type: 'image/svg+xml' }),
    fileName: getCutterFileName(sheet.widthCm, sheet.heightCm, 'svg')
  }
}

export function getCutterFileName(widthCm: number, heightCm: number, extension: string): string {
  return `cutter_montage_${formatNameNumber(widthCm)}x${formatNameNumber(heightCm)}cm.${extension}`
}

async function sourceToDataUrl(source: PieceSourceFile): Promise<string> {
  return `data:${source.mimeType};base64,${uint8ToBase64(source.bytes)}`
}

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = ''
  const chunkSize = 0x8000

  for (let index = 0; index < bytes.length; index += chunkSize) {
    const chunk = bytes.subarray(index, index + chunkSize)
    binary += String.fromCharCode(...chunk)
  }

  return btoa(binary)
}

function formatNameNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1).replace('.', '-')
}
