import type {
  CutterExportResult,
  CutterProject,
  PieceCutline,
  PieceSourceFile
} from '../types'
import {
  escapeXml,
  getPlacedArtworkRect,
  getPlacedCutlineRect,
  type CutlineRect
} from './cutlineGenerator'
import { getPlacedMaskRect, type MaskRect } from './maskUtils'

const CM_TO_MM = 10

export async function exportCutterSvg(project: CutterProject): Promise<CutterExportResult> {
  const { sheet, sources, pieces, placedPieces, layers, exportSettings } = project
  const pieceMap = new Map(pieces.map((piece) => [piece.id, piece]))
  const sourceMap = new Map(sources.map((source) => [source.id, source]))
  const artworkEntries = exportSettings.includeArtwork
    ? await Promise.all(
        placedPieces.map(async (placed) => {
          const piece = pieceMap.get(placed.presetId)
          const source = piece ? sourceMap.get(piece.sourceId) : undefined

          if (!piece || !source || !piece.objectVisibility.artwork) {
            return { definition: '', artwork: '' }
          }

          const artworkRect = scaleRectToMm(getPlacedArtworkRect(placed, piece))
          const href = await sourceToDataUrl(source)
          const clipId = `clip-piece-${safeXmlId(placed.id)}`
          const clippingEnabled = piece.clippingMaskEnabled ?? piece.mask.enabled
          const definition = clippingEnabled
            ? getMaskClipPathMarkup(
                clipId,
                scaleRectToMm(getPlacedMaskRect(placed, piece)),
                piece.mask.shape
              )
            : ''
          const clipAttribute = clippingEnabled ? ` clip-path="url(#${clipId})"` : ''

          return {
            definition,
            artwork: [
              `<g id="artwork-${safeXmlId(placed.id)}" data-piece="${escapeXml(piece.displayName)}">`,
              `<image href="${href}" x="${formatNumber(artworkRect.xCm)}" y="${formatNumber(artworkRect.yCm)}" width="${formatNumber(artworkRect.widthCm)}" height="${formatNumber(artworkRect.heightCm)}" preserveAspectRatio="none"${getRotationTransform(artworkRect)}${clipAttribute} />`,
              '</g>'
            ].join('')
          }
        })
      )
    : []
  const cutlineMarkup = exportSettings.includeCutlines
    ? placedPieces
        .map((placed) => {
          const piece = pieceMap.get(placed.presetId)

          return piece && piece.objectVisibility.cutline
            ? getCutlineSvgElementMm(scaleRectToMm(getPlacedCutlineRect(placed, piece)), piece.cutline)
            : ''
        })
        .filter(Boolean)
        .join('\n')
    : ''
  const widthMm = sheet.widthCm * CM_TO_MM
  const heightMm = sheet.heightCm * CM_TO_MM

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="${formatNumber(widthMm)}mm" height="${formatNumber(heightMm)}mm" viewBox="0 0 ${formatNumber(widthMm)} ${formatNumber(heightMm)}">
  <title>Cutter Montage ${sheet.widthCm}x${sheet.heightCm}cm</title>
  <desc>Generated by My Printer App by Maher Tka. Artwork may be clipped; CutContour geometry remains vector.</desc>
  <defs>
${artworkEntries.map((entry) => entry.definition).filter(Boolean).join('\n')}
  </defs>
  <g id="Artwork" inkscape:groupmode="layer" inkscape:label="Artwork" data-layer-visible="${layers.artwork}">
${artworkEntries.map((entry) => entry.artwork).filter(Boolean).join('\n')}
  </g>
  <g id="CutContour" inkscape:groupmode="layer" inkscape:label="${escapeXml(exportSettings.strokeName)}" data-spot-name="${escapeXml(exportSettings.strokeName)}" data-layer-visible="${layers.cutlines}">
${cutlineMarkup}
  </g>
</svg>`

  return {
    blob: new Blob([svg], { type: 'image/svg+xml' }),
    fileName: getCutterFileName(sheet.widthCm, sheet.heightCm, 'svg')
  }
}

export function getCutterFileName(widthCm: number, heightCm: number, extension: string): string {
  return `cutter_montage_${formatNameNumber(widthCm)}x${formatNameNumber(heightCm)}cm.${extension}`
}

function getCutlineSvgElementMm(rect: CutlineRect, cutline: PieceCutline): string {
  const className = safeXmlId(cutline.strokeName || 'CutContour')
  const common = `class="${className}" data-spot-name="${escapeXml(cutline.strokeName)}" data-spot-color="${escapeXml(cutline.strokeColor)}" fill="none" stroke="${escapeXml(cutline.strokeColor)}" stroke-width="${formatNumber(cutline.strokeWidthPt)}pt" vector-effect="non-scaling-stroke"`
  const rotation = getRotationTransform(rect)

  if (cutline.shape === 'ellipse') {
    return `<ellipse cx="${formatNumber(rect.xCm + rect.widthCm / 2)}" cy="${formatNumber(rect.yCm + rect.heightCm / 2)}" rx="${formatNumber(rect.widthCm / 2)}" ry="${formatNumber(rect.heightCm / 2)}"${rotation} ${common} />`
  }

  if (cutline.shape === 'rounded-rectangle') {
    const radius = Math.min(rect.widthCm, rect.heightCm) * 0.08
    return `<rect x="${formatNumber(rect.xCm)}" y="${formatNumber(rect.yCm)}" width="${formatNumber(rect.widthCm)}" height="${formatNumber(rect.heightCm)}" rx="${formatNumber(radius)}" ry="${formatNumber(radius)}"${rotation} ${common} />`
  }

  if (cutline.shape === 'custom-path' && cutline.customPathData) {
    const transform = `translate(${formatNumber(rect.xCm)} ${formatNumber(rect.yCm)}) scale(${formatNumber(rect.widthCm)} ${formatNumber(rect.heightCm)})`
    return `<path d="${escapeXml(cutline.customPathData)}" transform="${transform}" ${common} />`
  }

  return `<rect x="${formatNumber(rect.xCm)}" y="${formatNumber(rect.yCm)}" width="${formatNumber(rect.widthCm)}" height="${formatNumber(rect.heightCm)}"${rotation} ${common} />`
}

function getMaskClipPathMarkup(id: string, rect: MaskRect, shape: string): string {
  const transform = getRotationTransform(rect)

  if (shape === 'ellipse') {
    return `<clipPath id="${id}" clipPathUnits="userSpaceOnUse"><ellipse cx="${formatNumber(rect.xCm + rect.widthCm / 2)}" cy="${formatNumber(rect.yCm + rect.heightCm / 2)}" rx="${formatNumber(rect.widthCm / 2)}" ry="${formatNumber(rect.heightCm / 2)}"${transform} /></clipPath>`
  }

  if (shape === 'rounded-rectangle') {
    const radius = Math.min(rect.widthCm, rect.heightCm) * 0.08
    return `<clipPath id="${id}" clipPathUnits="userSpaceOnUse"><rect x="${formatNumber(rect.xCm)}" y="${formatNumber(rect.yCm)}" width="${formatNumber(rect.widthCm)}" height="${formatNumber(rect.heightCm)}" rx="${formatNumber(radius)}" ry="${formatNumber(radius)}"${transform} /></clipPath>`
  }

  if (shape === 'custom-polygon') {
    const points = [
      `${formatNumber(rect.xCm + rect.widthCm / 2)},${formatNumber(rect.yCm)}`,
      `${formatNumber(rect.xCm + rect.widthCm)},${formatNumber(rect.yCm + rect.heightCm / 2)}`,
      `${formatNumber(rect.xCm + rect.widthCm / 2)},${formatNumber(rect.yCm + rect.heightCm)}`,
      `${formatNumber(rect.xCm)},${formatNumber(rect.yCm + rect.heightCm / 2)}`
    ].join(' ')
    return `<clipPath id="${id}" clipPathUnits="userSpaceOnUse"><polygon points="${points}"${transform} /></clipPath>`
  }

  return `<clipPath id="${id}" clipPathUnits="userSpaceOnUse"><rect x="${formatNumber(rect.xCm)}" y="${formatNumber(rect.yCm)}" width="${formatNumber(rect.widthCm)}" height="${formatNumber(rect.heightCm)}"${transform} /></clipPath>`
}

async function sourceToDataUrl(source: PieceSourceFile): Promise<string> {
  return `data:${source.mimeType};base64,${uint8ToBase64(source.bytes)}`
}

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = ''
  const chunkSize = 0x8000

  for (let index = 0; index < bytes.length; index += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(index, index + chunkSize))
  }

  return btoa(binary)
}

function scaleRectToMm<T extends CutlineRect | MaskRect>(rect: T): T {
  return {
    ...rect,
    xCm: rect.xCm * CM_TO_MM,
    yCm: rect.yCm * CM_TO_MM,
    widthCm: rect.widthCm * CM_TO_MM,
    heightCm: rect.heightCm * CM_TO_MM
  }
}

function getRotationTransform(rect: CutlineRect | MaskRect): string {
  return rect.rotation
    ? ` transform="rotate(${formatNumber(rect.rotation)} ${formatNumber(rect.xCm + rect.widthCm / 2)} ${formatNumber(rect.yCm + rect.heightCm / 2)})"`
    : ''
}

function safeXmlId(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]/g, '-')
}

function formatNumber(value: number): string {
  return Number(value.toFixed(4)).toString()
}

function formatNameNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1).replace('.', '-')
}
