#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shobjidl.h>
#include <shlwapi.h>
#include <shellapi.h>
#include <strsafe.h>
#include <atomic>
#include <string>
#include <vector>
#include <algorithm>
#include <new>
#include <cstdio>

// Native, per-user Explorer command. Menu data is generated by fast-print-menu.ps1.
// No managed runtime, PDF decoding, or printer driver is loaded into Explorer.
static const CLSID CLSID_FastPrint = {0xd8335fe6,0xed4f,0x4386,{0x8e,0x87,0x69,0x52,0x7f,0x75,0xb4,0xef}};
static std::atomic<long> objects{0};
static std::atomic<long> locks{0};
static const std::wstring root = L"Software\\Classes\\MaherTka.FastPrint";

static void diagnostic(const char* event, long result) {
  DWORD enabled = 0, size = sizeof(enabled);
  if (RegGetValueW(HKEY_CURRENT_USER, root.c_str(), L"Diagnostics", RRF_RT_REG_DWORD, nullptr, &enabled, &size) != ERROR_SUCCESS || !enabled) return;
  wchar_t folder[MAX_PATH]; if (!GetTempPathW(MAX_PATH, folder)) return;
  std::wstring path = std::wstring(folder) + L"maher-fast-print-shell.log";
  HANDLE file = CreateFileW(path.c_str(), FILE_APPEND_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
  if (file == INVALID_HANDLE_VALUE) return;
  char row[256]; DWORD written;
  int count = sprintf_s(row, "%lu %s %ld\r\n", GetCurrentProcessId(), event, result);
  if (count > 0) WriteFile(file, row, count, &written, nullptr);
  CloseHandle(file);
}
static std::wstring value(const std::wstring& path, const wchar_t* name) {
  DWORD bytes = 0;
  if (RegGetValueW(HKEY_CURRENT_USER, path.c_str(), name, RRF_RT_REG_SZ, nullptr, nullptr, &bytes) != ERROR_SUCCESS) return L"";
  std::vector<wchar_t> data(bytes / sizeof(wchar_t) + 1);
  if (RegGetValueW(HKEY_CURRENT_USER, path.c_str(), name, RRF_RT_REG_SZ, nullptr, data.data(), &bytes) != ERROR_SUCCESS) return L"";
  return data.data();
}
static std::vector<std::wstring> children(const std::wstring& path) {
  std::vector<std::wstring> result;
  HKEY key;
  if (RegOpenKeyExW(HKEY_CURRENT_USER, (path + L"\\shell").c_str(), 0, KEY_READ, &key) != ERROR_SUCCESS) return result;
  for (DWORD index = 0;; ++index) {
    wchar_t name[256]; DWORD size = 256;
    const auto status = RegEnumKeyExW(key, index, name, &size, nullptr, nullptr, nullptr, nullptr);
    if (status == ERROR_NO_MORE_ITEMS) break;
    if (status == ERROR_SUCCESS) result.push_back(path + L"\\shell\\" + name);
  }
  RegCloseKey(key);
  std::sort(result.begin(), result.end());
  return result;
}
static HRESULT selectedFile(IShellItemArray* items, std::wstring& path) {
  if (!items) return E_INVALIDARG;
  DWORD count = 0;
  if (FAILED(items->GetCount(&count)) || count != 1) return E_INVALIDARG;
  IShellItem* item = nullptr;
  HRESULT hr = items->GetItemAt(0, &item);
  if (FAILED(hr)) return hr;
  PWSTR name = nullptr;
  hr = item->GetDisplayName(SIGDN_FILESYSPATH, &name);
  item->Release();
  if (SUCCEEDED(hr)) { path = name; CoTaskMemFree(name); }
  return hr;
}

class Command;
class Enumerator final : public IEnumExplorerCommand {
  std::atomic<ULONG> references{1};
  std::vector<std::wstring> paths;
  ULONG position = 0;
public:
  explicit Enumerator(std::vector<std::wstring> entries, ULONG offset = 0) : paths(std::move(entries)), position(offset) { ++objects; }
  ~Enumerator() { --objects; }
  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, void** result) override {
    if (!result) return E_POINTER; *result = nullptr;
    if (iid == IID_IUnknown || iid == __uuidof(IEnumExplorerCommand)) { *result = static_cast<IEnumExplorerCommand*>(this); AddRef(); return S_OK; }
    return E_NOINTERFACE;
  }
  ULONG STDMETHODCALLTYPE AddRef() override { return ++references; }
  ULONG STDMETHODCALLTYPE Release() override { ULONG n = --references; if (!n) delete this; return n; }
  HRESULT STDMETHODCALLTYPE Next(ULONG count, IExplorerCommand** commands, ULONG* fetched) override;
  HRESULT STDMETHODCALLTYPE Skip(ULONG count) override {
    ULONG skipped = (std::min)(count, static_cast<ULONG>(paths.size()) - position); position += skipped; return skipped == count ? S_OK : S_FALSE;
  }
  HRESULT STDMETHODCALLTYPE Reset() override { position = 0; return S_OK; }
  HRESULT STDMETHODCALLTYPE Clone(IEnumExplorerCommand** result) override {
    if (!result) return E_POINTER;
    *result = new(std::nothrow) Enumerator(paths, position); return *result ? S_OK : E_OUTOFMEMORY;
  }
};

class Command final : public IExplorerCommand {
  std::atomic<ULONG> references{1};
  std::wstring path;
  std::vector<std::wstring> entries;
public:
  explicit Command(std::wstring location) : path(std::move(location)), entries(children(path)) { ++objects; }
  ~Command() { --objects; }
  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, void** result) override {
    if (!result) return E_POINTER; *result = nullptr;
    if (iid == IID_IUnknown || iid == __uuidof(IExplorerCommand)) { *result = static_cast<IExplorerCommand*>(this); AddRef(); return S_OK; }
    return E_NOINTERFACE;
  }
  ULONG STDMETHODCALLTYPE AddRef() override { return ++references; }
  ULONG STDMETHODCALLTYPE Release() override { ULONG n = --references; if (!n) delete this; return n; }
  HRESULT STDMETHODCALLTYPE GetTitle(IShellItemArray*, PWSTR* title) override {
    const auto label = value(path, L"MUIVerb");
    return SHStrDupW(label.empty() ? L"Fast Print" : label.c_str(), title);
  }
  HRESULT STDMETHODCALLTYPE GetIcon(IShellItemArray*, PWSTR* icon) override {
    if (!icon) return E_POINTER; *icon = nullptr;
    const auto location = value(root, L"Icon");
    return location.empty() ? E_NOTIMPL : SHStrDupW(location.c_str(), icon);
  }
  HRESULT STDMETHODCALLTYPE GetToolTip(IShellItemArray*, PWSTR* tip) override {
    return SHStrDupW(L"Choose printer, paper, color, and pages per sheet.", tip);
  }
  HRESULT STDMETHODCALLTYPE GetCanonicalName(GUID* guid) override { if (!guid) return E_POINTER; *guid = CLSID_FastPrint; return S_OK; }
  HRESULT STDMETHODCALLTYPE GetState(IShellItemArray* items, BOOL, EXPCMDSTATE* state) override {
    if (!state) return E_POINTER; *state = ECS_HIDDEN;
    std::wstring file;
    if (FAILED(selectedFile(items, file))) return S_OK;
    std::wstring extension = PathFindExtensionW(file.c_str());
    std::transform(extension.begin(), extension.end(), extension.begin(), towlower);
    if (extension == L".pdf" || extension == L".png" || extension == L".jpg" || extension == L".jpeg") *state = ECS_ENABLED;
    return S_OK;
  }
  HRESULT STDMETHODCALLTYPE Invoke(IShellItemArray* items, IBindCtx*) override {
    if (!entries.empty()) return E_NOTIMPL;
    std::wstring command = value(path + L"\\command", L"");
    if (command.empty()) return E_FAIL;
    const auto placeholder = command.find(L"%1");
    if (placeholder != std::wstring::npos) {
      std::wstring file;
      HRESULT hr = selectedFile(items, file); if (FAILED(hr)) return hr;
      if (file.find(L'"') != std::wstring::npos) return E_INVALIDARG;
      command.replace(placeholder, 2, file);
    }
    // Launch directly, never through cmd.exe or PowerShell command interpolation.
    std::vector<wchar_t> buffer(command.begin(), command.end()); buffer.push_back(0);
    STARTUPINFOW startup{sizeof(startup)}; PROCESS_INFORMATION process{};
    if (!CreateProcessW(nullptr, buffer.data(), nullptr, nullptr, FALSE, CREATE_UNICODE_ENVIRONMENT, nullptr, nullptr, &startup, &process)) return HRESULT_FROM_WIN32(GetLastError());
    CloseHandle(process.hThread); CloseHandle(process.hProcess); return S_OK;
  }
  HRESULT STDMETHODCALLTYPE GetFlags(EXPCMDFLAGS* flags) override {
    if (!flags) return E_POINTER; *flags = entries.empty() ? ECF_DEFAULT : ECF_HASSUBCOMMANDS; return S_OK;
  }
  HRESULT STDMETHODCALLTYPE EnumSubCommands(IEnumExplorerCommand** result) override {
    if (!result) return E_POINTER;
    *result = new(std::nothrow) Enumerator(entries); return *result ? S_OK : E_OUTOFMEMORY;
  }
};
HRESULT Enumerator::Next(ULONG count, IExplorerCommand** commands, ULONG* fetched) {
  if (!commands || (!fetched && count != 1)) return E_POINTER;
  ULONG produced = 0;
  while (produced < count && position < paths.size()) {
    auto entry = new(std::nothrow) Command(paths[position]);
    if (!entry) { if (fetched) *fetched = produced; return E_OUTOFMEMORY; }
    commands[produced++] = entry; ++position;
  }
  if (fetched) *fetched = produced;
  return produced == count ? S_OK : S_FALSE;
}
class ShellMenu final : public IShellExtInit, public IContextMenu {
  std::atomic<ULONG> references{1};
  std::wstring file;
  std::vector<std::wstring> actions;
  HRESULT append(HMENU menu, const std::wstring& path, UINT first, UINT last, unsigned depth) {
    if (depth > 8) return E_FAIL;
    for (const auto& child : children(path)) {
      auto label = value(child, L"MUIVerb");
      MENUITEMINFOW info{sizeof(info)};
      info.fMask = MIIM_STRING;
      info.dwTypeData = const_cast<LPWSTR>(label.c_str());
      if (!children(child).empty()) {
        info.fMask |= MIIM_SUBMENU;
        info.hSubMenu = CreatePopupMenu();
        HRESULT hr = append(info.hSubMenu, child, first, last, depth + 1);
        if (FAILED(hr)) { DestroyMenu(info.hSubMenu); return hr; }
      } else {
        if (first + actions.size() > last) return E_FAIL;
        info.fMask |= MIIM_ID;
        info.wID = first + static_cast<UINT>(actions.size());
        actions.push_back(child);
      }
      if (!InsertMenuItemW(menu, GetMenuItemCount(menu), TRUE, &info)) {
        if (info.hSubMenu) DestroyMenu(info.hSubMenu);
        return HRESULT_FROM_WIN32(GetLastError());
      }
    }
    return S_OK;
  }
public:
  ShellMenu() { ++objects; diagnostic("Create shell menu", 0); } ~ShellMenu() { --objects; }
  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, void** result) override {
    if (!result) return E_POINTER; *result = nullptr;
    if (iid == IID_IUnknown || iid == IID_IShellExtInit) *result = static_cast<IShellExtInit*>(this);
    else if (iid == IID_IContextMenu) *result = static_cast<IContextMenu*>(this);
    else return E_NOINTERFACE;
    AddRef(); return S_OK;
  }
  ULONG STDMETHODCALLTYPE AddRef() override { return ++references; }
  ULONG STDMETHODCALLTYPE Release() override { ULONG n = --references; if (!n) delete this; return n; }
  HRESULT STDMETHODCALLTYPE Initialize(PCIDLIST_ABSOLUTE, IDataObject* data, HKEY) override {
    file.clear();
    if (!data) { diagnostic("Initialize missing selection", E_INVALIDARG); return E_INVALIDARG; }
    FORMATETC format{CF_HDROP, nullptr, DVASPECT_CONTENT, -1, TYMED_HGLOBAL};
    STGMEDIUM medium{};
    HRESULT hr = data->GetData(&format, &medium); diagnostic("Initialize file data", hr);
    if (FAILED(hr)) return hr;
    HDROP drop = reinterpret_cast<HDROP>(medium.hGlobal);
    if (DragQueryFileW(drop, 0xFFFFFFFF, nullptr, 0) == 1) {
      UINT length = DragQueryFileW(drop, 0, nullptr, 0);
      std::vector<wchar_t> name(length + 1);
      if (DragQueryFileW(drop, 0, name.data(), length + 1)) file = name.data();
    }
    ReleaseStgMedium(&medium);
    diagnostic("Initialize selection length", static_cast<long>(file.size())); return file.empty() ? E_INVALIDARG : S_OK;
  }
  HRESULT STDMETHODCALLTYPE QueryContextMenu(HMENU menu, UINT index, UINT first, UINT last, UINT flags) override {
    diagnostic("Query flags", flags);
    if ((flags & CMF_DEFAULTONLY) || file.empty()) return MAKE_HRESULT(SEVERITY_SUCCESS, 0, 0);
    std::wstring ext = PathFindExtensionW(file.c_str());
    std::transform(ext.begin(), ext.end(), ext.begin(), towlower);
    if (ext != L".pdf" && ext != L".png" && ext != L".jpg" && ext != L".jpeg") return MAKE_HRESULT(SEVERITY_SUCCESS, 0, 0);
    actions.clear();
    HMENU submenu = CreatePopupMenu();
    HRESULT hr = append(submenu, root, first, last, 0); diagnostic("Build menu", hr);
    if (FAILED(hr)) { DestroyMenu(submenu); return hr; }
    MENUITEMINFOW info{sizeof(info)};
    info.fMask = MIIM_STRING | MIIM_SUBMENU;
    info.dwTypeData = const_cast<LPWSTR>(L"Fast Print");
    info.hSubMenu = submenu;
    if (!InsertMenuItemW(menu, index, TRUE, &info)) { DestroyMenu(submenu); return HRESULT_FROM_WIN32(GetLastError()); }
    diagnostic("Menu commands added", static_cast<long>(actions.size())); return MAKE_HRESULT(SEVERITY_SUCCESS, 0, static_cast<USHORT>(actions.size()));
  }
  HRESULT STDMETHODCALLTYPE InvokeCommand(CMINVOKECOMMANDINFO* info) override {
    if (!info || HIWORD(info->lpVerb)) return E_INVALIDARG;
    const UINT index = LOWORD(info->lpVerb);
    if (index >= actions.size()) return E_INVALIDARG;
    IShellItem* item = nullptr; IShellItemArray* array = nullptr;
    HRESULT hr = SHCreateItemFromParsingName(file.c_str(), nullptr, IID_PPV_ARGS(&item));
    if (FAILED(hr)) return hr;
    hr = SHCreateShellItemArrayFromShellItem(item, IID_PPV_ARGS(&array));
    item->Release(); if (FAILED(hr)) return hr;
    Command command(actions[index]);
    hr = command.Invoke(array, nullptr);
    array->Release(); return hr;
  }
  HRESULT STDMETHODCALLTYPE GetCommandString(UINT_PTR, UINT type, UINT*, LPSTR text, UINT size) override {
    if (type == GCS_HELPTEXTW) return StringCchCopyW(reinterpret_cast<LPWSTR>(text), size, L"Print with the selected Fast Print preset");
    return E_NOTIMPL;
  }
};
class Factory final : public IClassFactory {
  std::atomic<ULONG> references{1};
public:
  Factory() { ++objects; } ~Factory() { --objects; }
  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, void** result) override {
    if (!result) return E_POINTER; *result = nullptr;
    if (iid == IID_IUnknown || iid == IID_IClassFactory) { *result = static_cast<IClassFactory*>(this); AddRef(); return S_OK; } return E_NOINTERFACE;
  }
  ULONG STDMETHODCALLTYPE AddRef() override { return ++references; }
  ULONG STDMETHODCALLTYPE Release() override { ULONG n = --references; if (!n) delete this; return n; }
  HRESULT STDMETHODCALLTYPE CreateInstance(IUnknown* outer, REFIID iid, void** result) override {
    if (outer) return CLASS_E_NOAGGREGATION;
    auto command = new(std::nothrow) ShellMenu(); if (!command) return E_OUTOFMEMORY;
    HRESULT hr = command->QueryInterface(iid, result); command->Release(); return hr;
  }
  HRESULT STDMETHODCALLTYPE LockServer(BOOL lock) override { if (lock) ++locks; else --locks; return S_OK; }
};
STDAPI DllGetClassObject(REFCLSID clsid, REFIID iid, void** result) {
  if (clsid != CLSID_FastPrint) return CLASS_E_CLASSNOTAVAILABLE;
  auto factory = new(std::nothrow) Factory(); if (!factory) return E_OUTOFMEMORY;
  HRESULT hr = factory->QueryInterface(iid, result); factory->Release(); return hr;
}
STDAPI DllCanUnloadNow() { return objects == 0 && locks == 0 ? S_OK : S_FALSE; }
