// Generated by `npm run license:keygen`. This public key is safe to ship.
export const LICENSE_PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAojFOV923FRBkeGOoXVmRH6JnQITTinSKnCSPrgY6Xo0=\n-----END PUBLIC KEY-----\n"
