import { generateKeyPairSync } from 'node:crypto'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

const PRIVATE_KEY_ENV = 'MPTK_LICENSE_PRIVATE_KEY_FILE'
const DEFAULT_PRIVATE_KEY_PATH = '.license-private/license-signing-private.pem'
const PUBLIC_KEY_SOURCE_PATH = 'src/main/license-public-key.ts'

async function main(): Promise<void> {
  const force = process.argv.slice(2).includes('--force')
  const privateKeyPath = resolve(
    process.env[PRIVATE_KEY_ENV] ?? DEFAULT_PRIVATE_KEY_PATH
  )
  const publicKeySourcePath = resolve(PUBLIC_KEY_SOURCE_PATH)

  if (existsSync(privateKeyPath) && !force) {
    throw new Error(
      `A private signing key already exists at ${privateKeyPath}. Use --force only when intentionally rotating every issued serial key.`
    )
  }

  const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    publicKeyEncoding: { type: 'spki', format: 'pem' }
  })

  await mkdir(dirname(privateKeyPath), { recursive: true })
  await mkdir(dirname(publicKeySourcePath), { recursive: true })
  await writeFile(privateKeyPath, privateKey, { encoding: 'utf-8', mode: 0o600 })
  await writeFile(
    publicKeySourcePath,
    `// Generated by \`npm run license:keygen\`. This public key is safe to ship.\nexport const LICENSE_PUBLIC_KEY_PEM = ${JSON.stringify(publicKey)}\n`,
    'utf-8'
  )

  console.log('Offline license signing keys are ready.')
  console.log(`Private key (keep secret): ${privateKeyPath}`)
  console.log(`Public key (ships in app): ${publicKeySourcePath}`)
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : 'Key generation failed.')
  process.exitCode = 1
})
